# Exercises for the course "Declarative Problem Solving Paradigms in AI"


In [1]:
# Imports (some dependency errors may appear, you can ignore them for now)
# !pip install cpmpy numpy --quiet

import cpmpy as cp
import numpy as np

## **Session 1: Introduction to CPMpy and Basic Modelling**

Welcome to the first exercise session of Declarative Problem Solving Paradigms in AI. In this session, we will be introducing you to constraint programming using the CPMpy framework and working through some modelling exercises. The goal is to help you become familiar with how to formulate/model combinatorial problems using CPMpy.

<!-- <strong>Plan for the session:</strong>
- Introductory Talk (~20 minutes): Introduction to CPMpy, constraint programming, and how combinatorial problems can be represented as models.
- Hands-on Exercises (~2 hours): Practice modelling problems using CPMpy through a series of guided exercises. -->

<strong>Useful Resources:</strong>

- CPMpy documentation: https://cpmpy.readthedocs.io/en/latest/index.html
- CPMpy quickstart: https://cpmpy.readthedocs.io/en/latest/modeling.html


### **Part 1: Short Introduction**


#### **What is Constraint Programming (CP)?**

Constraint Programming is a **declarative paradigm** for solving **combinatorial problems**. In CP, a problem is modelled by defining:

- **Decision Variables**: They represent the solution, as entities that their values need to be determined.
- **Domains**: The set of possible values for the decision variables.
- **Constraints**: Relationships between variables restricting their possible values.
- **Objective (Optional)**: If the problem includes an optimisation objective, we can define an objective to minimize or maximize.

CP allows you to focus on **what** needs to be satisfied, without specifying **how** to solve the problem.


#### **Imperative vs Declarative Programming**

To understand the difference between imperative and declarative programming, let's take a simple example:

We have two variables `x` and `y`, and we want to find their values such that:

- Their sum is equal to 7.
- `x` is greater than `y`.


In [2]:
x, y = 0, 0

print(
    f"Imperative Approach: We explicitly assign the variables to specific values: x={x} and y={y}"
)

print("... and we explicitly reassign it until we find the solution:")
found = False
for x in range(10):
    for y in range(10):
        if x + y == 7 and x > y:
            print(f"\nSolution found: x = {x}, y = {y}")
            found = True
            break
    if found:
        break

Imperative Approach: We explicitly assign the variables to specific values: x=0 and y=0
... and we explicitly reassign it until we find the solution:

Solution found: x = 4, y = 3


In [3]:
x, y = cp.intvar(0, 10, shape=2)

print(f"Declarative Approach: We define the variables x={x} and y={y} with their domains.")
print(
    "Notice that we don't explicitly set/assign any values to the variables. We simply define their domains (sets of possible values)."
)

print(
    "\n... and we model the problem declaratively (i.e. we do not specify how to find the correct assignment, but what the correct assignment should satisfy):\n"
)

model = cp.Model([
    x + y == 7,  # Their sum is 7
    x > y,  # x is greater than y
])

print(model)

print("\n... and we solve the problem:\n")
model.solve()

print(f"Solution: x = {x.value()}, y = {y.value()}")

Declarative Approach: We define the variables x=IV0 and y=IV1 with their domains.
Notice that we don't explicitly set/assign any values to the variables. We simply define their domains (sets of possible values).

... and we model the problem declaratively (i.e. we do not specify how to find the correct assignment, but what the correct assignment should satisfy):

Constraints:
    (IV0) + (IV1) == 7
    (IV0) > (IV1)
Objective: None

... and we solve the problem:

Solution: x = 4, y = 3


#### **What is CPMpy?**

CPMpy is a Constraint Programming library in Python, for **modelling** and **solving** combinatorial problems.

**Basic Model Structure**:

1. **Decision Variables**: Defined with `intvar()` for integers or `boolvar()` for booleans.
2. **Constraints**: Applied on variables using comparison operators (`==`, `!=`, `<`, `<=`, etc.) or [global constraints](https://cpmpy.readthedocs.io/en/latest/modeling.html#global-constraints) like `AllDifferent`.
3. **Solving**: Use `solve()` to find a solution.


#### **A Practical Example**

We need to solve a Sudoku puzzle. The goal of Sudoku is to fill a 9x9 grid with numbers so that each row, column and 3x3 section contain all the digits
between 1 and 9.
The given unsolved grid is the following:

```python
[
    [0, 0, 0,  2, 0, 5,  0, 0, 0],
    [0, 9, 0,  0, 0, 0,  7, 3, 0],
    [0, 0, 2,  0, 0, 9,  0, 6, 0],

    [2, 0, 0,  0, 0, 0,  4, 0, 9],
    [0, 0, 0,  0, 7, 0,  0, 0, 0],
    [6, 0, 9,  0, 0, 0,  0, 0, 1],

    [0, 8, 0,  4, 0, 0,  1, 0, 0],
    [0, 6, 3,  0, 0, 0,  0, 8, 0],
    [0, 0, 0,  6, 0, 8,  0, 0, 0]
]
```

The goal is to replace the 0s with acceptable numbers. How to obtain a solution?


In [4]:
# Data
input_grid = [  # 0 represents empty cells
    [0, 0, 0, 2, 0, 5, 0, 0, 0],
    [0, 9, 0, 0, 0, 0, 7, 3, 0],
    [0, 0, 2, 0, 0, 9, 0, 6, 0],
    [2, 0, 0, 0, 0, 0, 4, 0, 9],
    [0, 0, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 9, 0, 0, 0, 0, 0, 1],
    [0, 8, 0, 4, 0, 0, 1, 0, 0],
    [0, 6, 3, 0, 0, 0, 0, 8, 0],
    [0, 0, 0, 6, 0, 8, 0, 0, 0],
]
given = np.array(input_grid)

# Decision Variables
grid = cp.intvar(1, 9, shape=given.shape)  # Each cell can have a value between 1 and 9

# Model
model = cp.Model()

# Ensure cells with non-zero numbers in the initial setup won't be changed during the solving process.
model += grid[given != 0] == given[given != 0]  # numpy indexing

# No duplicate number in a row, for all rows
model += [cp.AllDifferent(row) for row in grid]
# No duplicate number in a column, for all columns
model += [cp.AllDifferent(col) for col in grid.T]  # numpy transpose

# No duplicate number in a block, for all blocks
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        model += cp.AllDifferent(grid[i : i + 3, j : j + 3])

# For block constraints: Alternative way with list comprehension
model += [
    cp.AllDifferent(grid[i : i + 3, j : j + 3])
    for i in range(0, 9, 3)
    for j in range(0, 9, 3)
]

# Solve
model.solve()

# Print solution
print(grid.value())

[[3 7 8 2 6 5 9 1 4]
 [5 9 6 8 1 4 7 3 2]
 [1 4 2 7 3 9 5 6 8]
 [2 1 7 3 8 6 4 5 9]
 [8 5 4 9 7 1 6 2 3]
 [6 3 9 5 4 2 8 7 1]
 [7 8 5 4 2 3 1 9 6]
 [4 6 3 1 9 7 2 8 5]
 [9 2 1 6 5 8 3 4 7]]


### **Part 2: Exercises**


#### **1. Five Floors Problem**

Baker, Cooper, Fletcher, Miller, and Smith live on the first five floors of an apartment house.
Baker does not live on the fifth floor.
Cooper does not live on the first floor.
Fletcher does not live on either the fifth or the first floor.
Miller lives on a higher floor than does Cooper.
Smith does not live on a floor adjacent to Fletcher's.
Fletcher does not live on a floor adjacent to Cooper's.
They all live on different floors.
Find the floors where these people live.


In [5]:
"""
TODO: Fill in the lower and upper bounds of the decision variables.

Hints:
- What are the possible values for each variable?
- Which are the possible floors for each person?

https://cpmpy.readthedocs.io/en/latest/modeling.html#decision-variables
"""
lb = 1  # lower bound
ub = 5  # upper bound

# Decision Variables
B = cp.intvar(lb, ub)  # Baker
C = cp.intvar(lb, ub)  # Cooper
F = cp.intvar(lb, ub)  # Fletcher
M = cp.intvar(lb, ub)  # Miller
S = cp.intvar(lb, ub)  # Smith

# Since all the decision variables have the same domain, we can also use a more convenient way to define them:
B, C, F, M, S = floors = cp.intvar(lb, ub, shape=5)

# Model
model = cp.Model()

# Constraints
"""
TODO: Fill in the constraints according to the problem description.

Hints:
1. https://cpmpy.readthedocs.io/en/latest/modeling.html#logical-constraints
2. https://cpmpy.readthedocs.io/en/latest/modeling.html#simple-comparison-constraints
3. https://cpmpy.readthedocs.io/en/latest/modeling.html#arithmetic-constraints
4. https://cpmpy.readthedocs.io/en/latest/modeling.html#global-constraints
"""
model += B != 5  # Baker does not live on the fifth floor
model += C != 1  # Cooper does not live on the first floor
model += (F != 1) & (
    F != 5
)  # Fletcher does not live on either the fifth or the first floor
model += M > C  # Miller lives on a higher floor than does Cooper
model += abs(S - F) > 1  # Smith does not live on a floor adjacent to Fletcher
model += abs(F - C) > 1  # Fletcher does not live on a floor adjacent to Cooper
model += cp.AllDifferent(B, C, F, M, S)  # They all live on different floors

# Solve
model.solve()

# Print solution
print(f"Baker lives on floor {B.value()}")
print(f"Cooper lives on floor {C.value()}")
print(f"Fletcher lives on floor {F.value()}")
print(f"Miller lives on floor {M.value()}")
print(f"Smith lives on floor {S.value()}")

Baker lives on floor 3
Cooper lives on floor 2
Fletcher lives on floor 4
Miller lives on floor 5
Smith lives on floor 1


#### **2. Bank Card**

My bank card has a 4 digit PIN, abcd. I use the following facts to help me remember it:

- no two digits are the same
- the 2-digit number cd is 3 times the 2-digit number ab
- the 2-digit number da is 2 times the 2-digit number bc

What is my PIN?


In [6]:
"""
TODO: Fill in the lower and upper bound of each digit.
What are the possible values (domain) of each digit?
"""
lb, ub = 0, 9  # lower bound and upper bound

# Decision Variables
a, b, c, d = digits = cp.intvar(lb, ub, shape=4)  # The four digits of the PIN

# Model
model = cp.Model()

# Constraints
"""
TODO: Fill in the constraints according to the problem description.
"""
model += cp.AllDifferent(a, b, c, d)  # no two digits are the same
model += (10 * c + d) == 3 * (10 * a + b)  # cd is 3 times ab
model += (10 * d + a) == 2 * (10 * b + c)  # da is 2 times bc

# Solve
model.solve()

# Print solution
print(f"PIN: {a.value()}{b.value()}{c.value()}{d.value()}")

PIN: 2163


#### **3. Coin Change**

Alice needs to give Bob exactly 1.99 euros in change. She has six different types of coins with the following values: 1, 2, 5, 10, 25, and 50 cents. However, she only has a limited number of each coin type: 20 coins of 1 cent, 10 coins of 2 cents, 15 coins of 5 cents, 8 coins of 10 cents, 4 coins of 25 cents, and 2 coins of 50 cents.

How can Alice give Bob the exact change using the **fewest number of coins possible** while respecting the availability of each coin type?


In [7]:
# Parameters of the problem
amount = 199  # in cents
coin_types = [1, 2, 5, 10, 25, 50]
available_coins = [20, 10, 15, 8, 4, 2]

# Decision Variables
coins = cp.intvar(0, max(available_coins), shape=len(coin_types))

# Model
model = cp.Model()

# Constraints
model += cp.sum(coins[i] * coin_types[i] for i in range(len(coin_types))) == amount
for i in range(len(coin_types)):
    model += coins[i] <= available_coins[i]

# Objective: Minimize the number of coins
model.minimize(cp.sum(coins))

# Solve
model.solve()

# Print solution
print("Coins used:")
for i, coin in enumerate(coin_types):
    print(f"{coins[i].value()} coin(s) of {coin} cents")
print(f"Total coins used: {sum(coins[i].value() for i in range(len(coin_types)))}")
print(
    f"Total amount: {sum(coins[i].value() * coin_types[i] for i in range(len(coin_types)))} cents"
)

Coins used:
0 coin(s) of 1 cents
2 coin(s) of 2 cents
0 coin(s) of 5 cents
2 coin(s) of 10 cents
3 coin(s) of 25 cents
2 coin(s) of 50 cents
Total coins used: 9
Total amount: 199 cents


#### **4. Magic Square**

A magic square is an $n \times n$ grid such that each cell contains a different integer from 1 to $n^2$ and the sum of the integers in each row, column and diagonal is equal.
Find a magic square for any size $n$, knowing that the sum of each row, column and diagonal has to be equal to $n(n^2 + 1)/2$ (an integer: div
operator). Remember there is no magic square for size 2.


<details>
  <summary>Click to reveal hint</summary>
  
```python
"""
An example to show how to use indexing for diagonals in matrices.

Suppose that we have a grid of integers, and we require every number in the main
diagonal to be different, and also every number in the secondary diagonal to be
different.
"""

# Parameters

n = 50

# Decision Variables

grid = cp.intvar(0, n, shape=(n, n))

# Constraints

model = cp.Model()

model += cp.AllDifferent(grid[i, i] for i in range(n)) # Every number in the main diagonal is different
model += cp.AllDifferent(grid[i, n - 1 - i] for i in range(50)) # Every number in the secondary diagonal is different

# Solve

model.solve()

```

</details>
```


In [8]:
def magic_square(n: int) -> None:
    assert n != 2, "Magic square is not defined for size 2"

    """
    TODO: define the magic sum as a function of n.
    Use // operator to get the integer part of a division (div operator).
    """
    magic_sum = n * (n**2 + 1) // 2  # sum of each row, column and diagonal

    # Decision Variables - TODO
    grid = cp.intvar(1, n**2, shape=(n, n))

    # Model
    model = cp.Model()

    # Constraints

    """
    TODO: Fill in the constraints according to the problem description.

    Hints:
    1. https://cpmpy.readthedocs.io/en/latest/api/expressions/globalconstraints.html#cpmpy.expressions.globalconstraints.AllDifferent
    2. https://cpmpy.readthedocs.io/en/latest/api/expressions/python_builtins.html#cpmpy.expressions.python_builtins.sum
    """

    # All numbers in the magic square must be different
    model += cp.AllDifferent(grid)

    # The sum of the numbers in each row must be equal to the magic sum
    model += [cp.sum(row) == magic_sum for row in grid]

    # The sum of the numbers in each column must be equal to the magic sum
    model += [cp.sum(col) == magic_sum for col in grid.T]

    # The sum of the numbers in the main diagonal must be equal to the magic sum
    model += cp.sum(grid[i, i] for i in range(n)) == magic_sum

    # The sum of the numbers in the other diagonal must be equal to the magic sum
    model += cp.sum(grid[i, n - i - 1] for i in range(n)) == magic_sum

    # Solve
    model.solve()

    # Print solution - TODO
    print("Magic Square:")
    for row in grid.value():
        print(" ".join(f"{num:3d}" for num in row))
    print(f"\nMagic Sum: {magic_sum}")


# Test
magic_square(5)

Magic Square:
 10   1  20  12  22
 16  17  13  14   5
 19  23   6   8   9
 18  21  15   7   4
  2   3  11  24  25

Magic Sum: 65


#### **5. Movie Scheduling**:

Consider the following scheduling problem. Imagine you are a highly-in-
demand actor, who has been presented with offers to star in n different movie
projects under development. Each offer comes specified with the first and last day of filming. To take the job, you must commit to being available throughout this entire period. Thus, you cannot simultaneously accept two jobs whose intervals overlap.
For an artist such as yourself, the criteria for job acceptance is clear: you want to make as much money as possible. Because each of these films pays the same fee per film, this implies you seek the largest possible set of jobs (intervals) such that no two of them conflict with each other.

Here is the list of movies along with their first and last day of filming:

```
movies = [  # title, start, end
    ["Tarjan of the Jungle", 4, 13],
    ["The Four Volume Problem", 17, 27],
    ["The President's Algorist", 1, 10],
    ["Steiner's Tree", 12, 18],
    ["Process Terminated", 23, 30],
    ["Halting State", 9, 16],
    ["Programming Challenges", 19, 25],
    ["Discrete Mathematics", 2, 7],
    ["Calculated Bets", 26, 31]
]
```

Which movies would you choose to maximize your income?


In [9]:
movies = [  # title, start, end
    ["Tarjan of the Jungle", 4, 13],
    ["The Four Volume Problem", 17, 27],
    ["The President's Algorist", 1, 10],
    ["Steiner's Tree", 12, 18],
    ["Process Terminated", 23, 30],
    ["Halting State", 9, 16],
    ["Programming Challenges", 19, 25],
    ["Discrete Mathematics", 2, 7],
    ["Calculated Bets", 26, 31],
]

# Decision Variables - TODO
selected = cp.boolvar(shape=len(movies))
income = cp.intvar(0, len(movies))

# Model
model = cp.Model()

# Constraints - TODO
for i in range(len(movies)):
    for j in range(i + 1, len(movies)):
        if movies[i][1] < movies[j][2] and movies[i][2] > movies[j][1]:
            model += ~(selected[i] & selected[j])  # overlap

# Set income to be the sum of selected movies
model += income == cp.sum(selected)

# Objective - TODO
model.maximize(income)

# Solve
model.solve()

# Print solution - TODO
print("Selected movies:")
for i, movie in enumerate(sorted(movies, key=lambda x: x[1])):
    if selected[movies.index(movie)].value():
        print(f"- {movie[0]} (Days {movie[1]}-{movie[2]})")
print(f"Income: {income.value()}")

Selected movies:
- Discrete Mathematics (Days 2-7)
- Halting State (Days 9-16)
- Programming Challenges (Days 19-25)
- Calculated Bets (Days 26-31)
Income: 4


#### **6. Robbery**

Following a robbery, an inspector interviewed six suspects. The getaway car had been barely big enough to hold two, so she reckoned that at least four of them were innocent. She also supposed that the innocent ones would tell the truth, while the guilty one or ones would lie. What they actually said was:

- ARTIE: "It wasn't me."
- BILL: "Crackitt was in it up to his neck."
- CRACKITT: "No I wasn't."
- DODGY: "If Crackitt did it, Bill did it with him."
- EDGY: "Nobody did it alone."
- FINGERS: "It was Artie and Dodgy together."

Who is guilty?


<details>
  <summary>Click to reveal hint</summary>

**Logic Truth Table:**

| p     | q     | ¬p    | p ∧ q | p ∨ q | p → q | p ↔ q |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| True  | True  | False | True  | True  | True  | True  |
| True  | False | False | False | True  | False | False |
| False | True  | True  | False | True  | True  | False |
| False | False | True  | False | False | True  | True  |

**Explanation of Symbols:**

- ¬p: Negation (NOT p)
- p ∧ q: Conjunction (AND)
- p ∨ q: Disjunction (OR)
- p → q: Implication (If p then q)
- p ↔ q: Biconditional (p if and only if q)

</details>


In [10]:
# Decision Variables - TODO
A, B, C, D, E, F = cp.boolvar(shape=6, name="guilty")

# Model
model = cp.Model()

# Constraints - TODO
guilty_total = cp.sum((A, B, C, D, E, F))
model += guilty_total <= 2
model += (
    (~A | A)  # Artie
    & (C | B)  # Bill
    & (~C | C)  # Crackitt
    & (C.implies(B) | D)  # Dodgy
    & ((guilty_total > 1) | E)  # Edgy
    & ((A & D) | F)  # Fingers
)

# Solve
model.solve()

# Print solution - TODO
print("Guilty:", [name for name, var in zip(["Artie", "Bill", "Crackitt", "Dodgy", "Edgy", "Fingers"],
                                            [A, B, C, D, E, F])
                  if var.value()])

Guilty: ['Bill', 'Fingers']


#### **Extra Exercises**

> The following exercises are **extra practice** problems. They will **not be covered** during the regular exercise sessions. However, they offer a great opportunity to practice more. You are encouraged to try them at home to challenge yourself further!


##### **Extra 1: Send More Money**

The "Send More Money" puzzle is a classic cryptarithmetic problem where each letter represents a unique digit. The goal is to assign digits to the letters such that the following equation holds true:

```
   SEND
 + MORE
 ------
  MONEY
```

Each letter must be assigned a unique digit from 0 to 9, and the first letter of each word cannot be zero. What is the digit assigned to each letter?


In [11]:
# Decision Variables - TODO
S, E, N, D, M, O, R, Y = cp.intvar(0, 9, shape=8)

# Model
model = cp.Model()

# Constraints - TODO
model += cp.AllDifferent(S, E, N, D, M, O, R, Y)
model += S > 0
model += M > 0


# The summation constraint
def additionfn(*letter) -> int:
    return sum(10**i * letter for i, letter in enumerate(reversed(letter)))


model += additionfn(S, E, N, D) + additionfn(M, O, R, E) == additionfn(M, O, N, E, Y)

# Solve
model.solve()

# Print solution - TODO
print(
    f"S={S.value()}, E={E.value()}, N={N.value()}, D={D.value()}, M={M.value()}, O={O.value()}, R={R.value()}, Y={Y.value()}"
)
print()
print(f"  {S.value()}{E.value()}{N.value()}{D.value()}")
print(f"+ {M.value()}{O.value()}{R.value()}{E.value()}")
print("------")
print(f" {M.value()}{O.value()}{N.value()}{E.value()}{Y.value()}")

S=9, E=5, N=6, D=7, M=1, O=0, R=8, Y=2

  9567
+ 1085
------
 10652


##### **Extra 2: Minesweeper**

Numbers and mines are randomly distributed in a given board.
The number on a cell shows the exact number of mines around this cell in all 8 directions: top, top-right, right, bottom-right, bottom, bottom-left, left, top-left.

The task is to determine which cells contain mines, the initial board is given below.


<details>
  <summary>Click to reveal hint</summary>

```python
"""
An example to show how to find neighbors (top, right, bottom, left) of a cell in a grid.
"""

n = 4  # 4x4 grid
grid = cp.boolvar(shape=(n, n))

model = cp.Model()

for i in range(n):
    for j in range(n):
        # Collect neighbors for each cell
        neighbors = []
        for a, b in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
            if 0 <= i + a < n and 0 <= j + b < n:
                neighbors.append(grid[i + a, j + b])

        print(f"Neighbors of cell {grid[i, j]}: {neighbors}")

print("The grid:")
print(grid)
```

</details>


In [12]:
# Data
X = -1
game = np.array(
    [  # 0-8: number of mines around, -1: not opened
        [2, 3, X, 2, 2, X, 2, 1],
        [X, X, 4, X, X, 4, X, 2],
        [X, X, X, X, X, X, 4, X],
        [X, 5, X, 6, X, X, X, 2],
        [2, X, X, X, 5, 5, X, 2],
        [1, 3, 4, X, X, X, 4, X],
        [0, 1, X, 4, X, X, X, 3],
        [0, 1, 2, X, 2, 3, X, 2],
    ]
)


# Decision Variables - TODO
n = 8  # 8x8 grid
grid = cp.boolvar(shape=(n, n))

# Model
model = cp.Model()

# Constraints - TODO
coords = [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)]
for i in range(n):
    for j in range(n):
        if game[i, j] != X:
            model += (
                cp.sum(
                    grid[i + a, j + b]
                    for a, b in coords
                    if 0 <= i + a < n and 0 <= j + b < n
                )
                == game[i, j]
            )

# Solve
model.solve()

# Print solution - TODO
print("Mine locations (1 indicates a mine):")
print(np.array([[int(grid[i, j].value()) for j in range(n)] for i in range(n)]))

print()
print("Game:")
print(game)

Mine locations (1 indicates a mine):
[[1 1 0 0 0 0 0 0]
 [1 0 1 1 0 1 1 0]
 [1 0 1 1 1 1 1 0]
 [1 0 0 1 1 1 0 0]
 [0 1 1 1 0 0 1 0]
 [0 0 0 0 1 0 1 0]
 [0 0 1 0 0 1 1 1]
 [0 0 0 1 1 0 0 1]]

Game:
[[ 2  3 -1  2  2 -1  2  1]
 [-1 -1  4 -1 -1  4 -1  2]
 [-1 -1 -1 -1 -1 -1  4 -1]
 [-1  5 -1  6 -1 -1 -1  2]
 [ 2 -1 -1 -1  5  5 -1  2]
 [ 1  3  4 -1 -1 -1  4 -1]
 [ 0  1 -1  4 -1 -1 -1  3]
 [ 0  1  2 -1  2  3 -1  2]]
